[package]
name = "risl-macros"
description = "Implements the procedural macros used by the RISL standard library"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
ar = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true, features = ["serde", "std"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }
rustc-hash = { workspace = true }

[dependencies.syn]
workspace = true
features = [
    "full",
    "visit",
    "visit-mut"
]
