[package]
name = "risl-request"
description = "Proc-macro utility library that allows you to make requests for shader compilation from RISL compiler."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ar = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true, features = ["serde", "std"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }
risl-smi = { workspace = true }

[dependencies.syn]
workspace = true
features = [
    "full",
    "visit",
    "visit-mut"
]
