[package]
name = "risl_cargo"
description = "Command line interface for RISL"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cargo = { workspace = true }
cargo-util = { workspace = true }
color-print = { workspace = true }
